// add action type constants i.e.:

// export const ACTION_DESCRIPTION = "ACTION_DESCRIPTION";

export const ADD_SUMMONER_DATA = "ADD_SUMMONER_DATA";
export const ADD_MATCH_HISTORY = "ADD_MATCH_HISTORY";
export const ADD_CHAMPION_DATA = "ADD_CHAMPION_DATA";
export const ADD_LEADERBOARD_DATA = "ADD_LEADERBOARD_DATA";
export const ADD_VALORANT_DATA = "ADD_VALORANT_DATA";
export const ADD_TFT_DATA = "ADD_TFT_DATA";