// add action type constants i.e.:

// export const ACTION_DESCRIPTION = "ACTION_DESCRIPTION";

export const ADD_SUMMONER_DATA = "ADD_SUMMONER_DATA";
export const ADD_CHAMPION_DATA = "ADD_CHAMPION_DATA";
export const ADD_LEADERBOARD_DATA = "ADD_LEADERBOARD_DATA";
export const ADD_VALORANT_DATA = "ADD_VALORANT_DATA";
export const ADD_TFT_DATA = "ADD_TFT_DATA";
export const ADD_SUMM_CHAMP_DATA = "ADD_SUMM_CHAMP_DATA";
export const ADD_TFTDDBOX_DATA = "ADD_TFTDDBOX_DATA";